on: push
name: Deploy on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ki368215.ftp.tools
        username: ki368215_github
        password: ${{ secrets.ftp_password }}
